/**
 * Core type definitions for the ArenaPulse AI system.
 *
 * Defines interfaces for stadium zones, telemetry events,
 * AI incident responses, and match information.
 *
 * @module types
 */

/** Operational status level for a stadium zone */
export type ZoneStatus = "normal" | "elevated" | "critical";

/** Incident severity classification */
export type Severity = "CRITICAL" | "WARNING" | "INFO";

/** Represents a physical zone within the stadium */
export interface StadiumZone {
  id: string;
  name: string;
  capacity: number;
  currentOccupancy: number;
  status: ZoneStatus;
  waitTimeMinutes: number;
  gates: string[];
  transitLines: string[];
}

/** A real-time telemetry event from a stadium sensor/system */
export interface TelemetryEvent {
  id: string;
  timestamp: string;
  zoneId: string;
  eventType: "crowd_spike" | "gate_failure" | "transit_delay" | "weather_alert" | "medical" | "normal";
  description: string;
  severity: Severity;
  metrics: {
    density: number;
    waitTime: number;
    flowRate: number;
  };
}

/** Crowd rerouting instructions generated by AI */
export interface ReroutingAction {
  triggerDynamicRerouting: boolean;
  divertFrom: string;
  divertTo: string;
  routingInstructions: string;
}

/** Volunteer deployment plan generated by AI */
export interface VolunteerDeployment {
  actionRequired: boolean;
  quantityToDeploy: number;
  targetLocation: string;
  briefingMessage: string;
}

/** Multilingual public announcements (English, Spanish, French) */
export interface PublicAnnouncements {
  en: string;
  es: string;
  fr: string;
}

/** Metadata about the AI processing mode */
export interface AIMeta {
  mode: "gemini-live" | "fallback";
  model: string;
}

/** Complete AI incident analysis response */
export interface AIIncidentResponse {
  incidentId: string;
  severity: Severity;
  affectedZone: string;
  rootCause: string;
  operationalImpact: string;
  reroutingAction: ReroutingAction;
  volunteerDeployment: VolunteerDeployment;
  publicAnnouncements: PublicAnnouncements;
  timestamp: string;
  _meta?: AIMeta;
}

/** Match metadata for the current event */
export interface MatchInfo {
  homeTeam: string;
  awayTeam: string;
  venue: string;
  city: string;
  kickoffTime: string;
  attendance: number;
}
